<a href="https://colab.research.google.com/github/sinnu2004/MLProjects/blob/main/KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [330]:
import numpy as np
import pandas as pd

In [331]:
df = pd.read_csv("/content/Breast_Cancer.csv")

In [332]:
df.head()

,Age,Race,Marital Status,T Stage,N Stage,6th Stage,differentiate,Grade,A Stage,Tumor Size,Estrogen Status,Progesterone Status,Regional Node Examined,Reginol Node Positive,Survival Months,Status
0,68,White,Married,T1,N1,IIA,Poorly differentiated,3,Regional,4,Positive,Positive,24,1,60,Alive
1,50,White,Married,T2,N2,IIIA,Moderately differentiated,2,Regional,35,Positive,Positive,14,5,62,Alive
2,58,White,Divorced,T3,N3,IIIC,Moderately differentiated,2,Regional,63,Positive,Positive,14,7,75,Alive
3,58,White,Married,T1,N1,IIA,Poorly differentiated,3,Regional,18,Positive,Positive,2,1,84,Alive
4,47,White,Married,T2,N1,IIB,Poorly differentiated,3,Regional,41,Positive,Positive,3,1,50,Alive

In [333]:
df.isnull().sum()

Age                       0
Race                      0
Marital Status            0
T Stage                   0
N Stage                   0
6th Stage                 0
differentiate             0
Grade                     0
A Stage                   0
Tumor Size                0
Estrogen Status           0
Progesterone Status       0
Regional Node Examined    0
Reginol Node Positive     0
Survival Months           0
Status                    0
dtype: int64

In [334]:
df['Race'].unique()

array(['White', 'Black', 'Other'], dtype=object)

In [335]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
encode = encoder.fit_transform(df['Race'])
encode = pd.DataFrame(encode)

In [336]:
df['Race'] = encode

In [337]:
df.head(1)

,Age,Race,Marital Status,T Stage,N Stage,6th Stage,differentiate,Grade,A Stage,Tumor Size,Estrogen Status,Progesterone Status,Regional Node Examined,Reginol Node Positive,Survival Months,Status
0,68,2,Married,T1,N1,IIA,Poorly differentiated,3,Regional,4,Positive,Positive,24,1,60,Alive

In [338]:
df = df.drop(columns=['Marital Status'])

In [339]:
df['T Stage '].unique()

array(['T1', 'T2', 'T3', 'T4'], dtype=object)

In [340]:
encode = encoder.fit_transform(df['T Stage '])
encode = pd.DataFrame(encode)
df['T Stage '] = encode

In [341]:
df['N Stage'].unique()

array(['N1', 'N2', 'N3'], dtype=object)

In [342]:
encode = encoder.fit_transform(df['N Stage'])
encode = pd.DataFrame(encode)
df['N Stage'] = encode

In [343]:
df['6th Stage'].unique()

array(['IIA', 'IIIA', 'IIIC', 'IIB', 'IIIB'], dtype=object)

In [344]:
df['differentiate'].unique()

array(['Poorly differentiated', 'Moderately differentiated',
       'Well differentiated', 'Undifferentiated'], dtype=object)

In [345]:
encode = encoder.fit_transform(df['differentiate'])
encode = pd.DataFrame(encode)
df['differentiate'] = encode

In [346]:
df['A Stage'].unique()

array(['Regional', 'Distant'], dtype=object)

In [347]:
encode = encoder.fit_transform(df['A Stage'])
encode = pd.DataFrame(encode)
df['A Stage'] = encode

In [348]:
df.head(1)

,Age,Race,T Stage,N Stage,6th Stage,differentiate,Grade,A Stage,Tumor Size,Estrogen Status,Progesterone Status,Regional Node Examined,Reginol Node Positive,Survival Months,Status
0,68,2,0,0,IIA,1,3,1,4,Positive,Positive,24,1,60,Alive

In [349]:
df['Estrogen Status'].unique()

array(['Positive', 'Negative'], dtype=object)

In [350]:
encode = encoder.fit_transform(df['Estrogen Status'])
encode = pd.DataFrame(encode)
df['Estrogen Status'] = encode

In [351]:
df['Progesterone Status'].unique()

array(['Positive', 'Negative'], dtype=object)

In [352]:
encode = encoder.fit_transform(df['Progesterone Status'])
encode = pd.DataFrame(encode)
df['Progesterone Status'] = encode

In [353]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
encode = label_encoder.fit_transform(df['Grade'])
encode = pd.DataFrame(encode)
df['Grade'] = encode

In [354]:
df = df.drop(columns=['6th Stage'])

In [355]:
df.head(1)

,Age,Race,T Stage,N Stage,differentiate,Grade,A Stage,Tumor Size,Estrogen Status,Progesterone Status,Regional Node Examined,Reginol Node Positive,Survival Months,Status
0,68,2,0,0,1,3,1,4,1,1,24,1,60,Alive

In [356]:
x = df.drop(columns='Status')
y = df['Status']

In [357]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=42)

In [358]:
x_train

,Age,Race,T Stage,N Stage,differentiate,Grade,A Stage,Tumor Size,Estrogen Status,Progesterone Status,Regional Node Examined,Reginol Node Positive,Survival Months
3841,62,2,0,1,1,3,1,16,1,1,18,6,67
1511,55,2,1,2,0,2,1,50,1,1,13,10,53
1717,49,2,0,0,0,2,1,20,1,1,6,1,56
226,59,2,2,1,0,2,1,57,1,1,20,9,60
2872,64,2,2,0,0,2,1,83,1,1,8,2,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1130,63,2,0,0,0,2,1,15,0,0,17,1,52
1294,46,2,0,0,0,2,1,20,1,1,6,2,58
860,57,2,1,0,3,1,1,22,1,1,31,2,45
3507,48,1,1,0,1,3,1,28,1,1,27,1,102
3174,53,2,1,0,1,3,1,27,1,1,14,2,104

In [359]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2816 entries, 3841 to 3174
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Age                     2816 non-null   int64
 1   Race                    2816 non-null   int64
 2   T Stage                 2816 non-null   int64
 3   N Stage                 2816 non-null   int64
 4   differentiate           2816 non-null   int64
 5   Grade                   2816 non-null   int64
 6   A Stage                 2816 non-null   int64
 7   Tumor Size              2816 non-null   int64
 8   Estrogen Status         2816 non-null   int64
 9   Progesterone Status     2816 non-null   int64
 10  Regional Node Examined  2816 non-null   int64
 11  Reginol Node Positive   2816 non-null   int64
 12  Survival Months         2816 non-null   int64
dtypes: int64(13)
memory usage: 308.0 KB

In [360]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [361]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=5)
model.fit(x_train,y_train)

KNeighborsClassifier()

In [362]:
pred = model.predict(x_test)

In [363]:
pred = pd.DataFrame(pred)

In [364]:
pred

          0
0     Alive
1     Alive
2      Dead
3     Alive
4     Alive
...     ...
1203  Alive
1204  Alive
1205  Alive
1206   Dead
1207  Alive

[1208 rows x 1 columns]

In [365]:
print("Training Score :",model.score(x_train,y_train)*100)
print("Testing Score :",model.score(x_test,y_test)*100)

Training Score : 89.9502840909091
Testing Score : 87.66556291390728

In [366]:
from sklearn.metrics import confusion_matrix,classification_report
print("Confusion Matrix",confusion_matrix(y_test,pred))

Confusion Matrix [[1000   33]
 [ 116   59]]

In [367]:
print("Classification Report",classification_report(y_test,pred))

Classification Report               precision    recall  f1-score   support

       Alive       0.90      0.97      0.93      1033
        Dead       0.64      0.34      0.44       175

    accuracy                           0.88      1208
   macro avg       0.77      0.65      0.69      1208
weighted avg       0.86      0.88      0.86      1208

In [368]:
from sklearn.metrics import f1_score, recall_score, precision_score, accuracy_score

print("f1 Score :", f1_score(y_test, pred, pos_label='Dead'))
print("recall score:", recall_score(y_test, pred, pos_label='Dead'))
print("precision score:", precision_score(y_test, pred, pos_label='Dead'))
print("accuracy score:", accuracy_score(y_test, pred))

f1 Score : 0.4419475655430712
recall score: 0.33714285714285713
precision score: 0.6413043478260869
accuracy score: 0.8766556291390728